using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NLayerTemplate.Data.Model.ContosoUniversity;

namespace NLayerTemplate.Data.Model
{
    public partial class TestCourse
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // Primary key values are provided by the user rather than generated by the database.
        [Display(Name = "Number")]
        public int TestCourseId { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 3)]
        public string Title { get; set; } = string.Empty;

        [Range(0, 5)]
        public int Credits { get; set; }

        public int TestDepartmentId { get; set; }

        public TestDepartment TestDepartment { get; set; } = default!;

        // A course can have any number of students enrolled in it, so the TestEnrollments navigation property is a collection.
        public ICollection<TestEnrollment> TestEnrollments { get; set; } = [];

        // A course may be taught by multiple instructors, so the TestCourseAssignments navigation property is a collection.
        public ICollection<TestCourseAssignment> TestCourseAssignments { get; set; } = [];
    }
}
