// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleMonolithTemplate.Monolith.Data.Persistence;

#nullable disable

namespace SimpleMonolithTemplate.Monolith.Migrations
{
    [DbContext(typeof(SimpleMonolithTemplateDbContext))]
    [Migration("20260930200308_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestCourse", b =>
                {
                    b.Property<int>("TestCourseId")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("TestDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TestCourseId");

                    b.HasIndex("TestDepartmentId");

                    b.ToTable("TestCourse", (string)null);
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestCourseAssignment", b =>
                {
                    b.Property<int>("TestCourseId")
                        .HasColumnType("int");

                    b.Property<int>("TestInstructorId")
                        .HasColumnType("int");

                    b.HasKey("TestCourseId", "TestInstructorId");

                    b.HasIndex("TestInstructorId");

                    b.ToTable("TestCourseAssignment", (string)null);
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestDepartment", b =>
                {
                    b.Property<int>("TestDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestDepartmentId"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("money");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TestInstructorId")
                        .HasColumnType("int");

                    b.HasKey("TestDepartmentId");

                    b.HasIndex("TestInstructorId");

                    b.ToTable("TestDepartment", (string)null);
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestEnrollment", b =>
                {
                    b.Property<int>("TestEnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestEnrollmentId"));

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("TestCourseId")
                        .HasColumnType("int");

                    b.Property<int>("TestStudentId")
                        .HasColumnType("int");

                    b.HasKey("TestEnrollmentId");

                    b.HasIndex("TestCourseId");

                    b.HasIndex("TestStudentId");

                    b.ToTable("TestEnrollment", (string)null);
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestInstructor", b =>
                {
                    b.Property<int>("TestInstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestInstructorId"));

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TestInstructorId");

                    b.ToTable("TestInstructor", (string)null);
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestOfficeAssignment", b =>
                {
                    b.Property<int>("TestInstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TestInstructorId");

                    b.ToTable("TestOfficeAssignment", (string)null);
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestStudent", b =>
                {
                    b.Property<int>("TestStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestStudentId"));

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<string>("GovernmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("TestEnrollmentDate")
                        .HasColumnType("date");

                    b.HasKey("TestStudentId");

                    b.ToTable("TestStudent", (string)null);
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestCourse", b =>
                {
                    b.HasOne("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestDepartment", "TestDepartment")
                        .WithMany("TestCourses")
                        .HasForeignKey("TestDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestDepartment");
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestCourseAssignment", b =>
                {
                    b.HasOne("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestCourse", "TestCourse")
                        .WithMany("TestCourseAssignments")
                        .HasForeignKey("TestCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestInstructor", "TestInstructor")
                        .WithMany("TestCourseAssignments")
                        .HasForeignKey("TestInstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCourse");

                    b.Navigation("TestInstructor");
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestDepartment", b =>
                {
                    b.HasOne("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestInstructor", "Administrator")
                        .WithMany()
                        .HasForeignKey("TestInstructorId");

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestEnrollment", b =>
                {
                    b.HasOne("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestCourse", "TestCourse")
                        .WithMany("TestEnrollments")
                        .HasForeignKey("TestCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestStudent", "TestStudent")
                        .WithMany("TestEnrollments")
                        .HasForeignKey("TestStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCourse");

                    b.Navigation("TestStudent");
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestOfficeAssignment", b =>
                {
                    b.HasOne("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestInstructor", "TestInstructor")
                        .WithOne("TestOfficeAssignment")
                        .HasForeignKey("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestOfficeAssignment", "TestInstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestInstructor");
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestCourse", b =>
                {
                    b.Navigation("TestCourseAssignments");

                    b.Navigation("TestEnrollments");
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestDepartment", b =>
                {
                    b.Navigation("TestCourses");
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestInstructor", b =>
                {
                    b.Navigation("TestCourseAssignments");

                    b.Navigation("TestOfficeAssignment");
                });

            modelBuilder.Entity("SimpleMonolithTemplate.Monolith.Data.Entities.ContosoUniversity.TestStudent", b =>
                {
                    b.Navigation("TestEnrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
