// <auto-generated />
using System;
using CleanArchitectureTemplate.Infrastructure.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitectureTemplate.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260930014313_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestCourse", b =>
                {
                    b.Property<int>("TestCourseId")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("TestDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TestCourseId");

                    b.HasIndex("TestDepartmentId");

                    b.ToTable("TestCourse", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestCourseAssignment", b =>
                {
                    b.Property<int>("TestCourseId")
                        .HasColumnType("int");

                    b.Property<int>("TestInstructorId")
                        .HasColumnType("int");

                    b.HasKey("TestCourseId", "TestInstructorId");

                    b.HasIndex("TestInstructorId");

                    b.ToTable("TestCourseAssignment", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestDepartment", b =>
                {
                    b.Property<int>("TestDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestDepartmentId"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("money");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TestInstructorId")
                        .HasColumnType("int");

                    b.HasKey("TestDepartmentId");

                    b.HasIndex("TestInstructorId");

                    b.ToTable("TestDepartment", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestEnrollment", b =>
                {
                    b.Property<int>("TestEnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestEnrollmentId"));

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("TestCourseId")
                        .HasColumnType("int");

                    b.Property<int>("TestStudentId")
                        .HasColumnType("int");

                    b.HasKey("TestEnrollmentId");

                    b.HasIndex("TestCourseId");

                    b.HasIndex("TestStudentId");

                    b.ToTable("TestEnrollment", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestInstructor", b =>
                {
                    b.Property<int>("TestInstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestInstructorId"));

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TestInstructorId");

                    b.ToTable("TestInstructor", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestOfficeAssignment", b =>
                {
                    b.Property<int>("TestInstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TestInstructorId");

                    b.ToTable("TestOfficeAssignment", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestStudent", b =>
                {
                    b.Property<int>("TestStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestStudentId"));

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<string>("GovernmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("TestEnrollmentDate")
                        .HasColumnType("date");

                    b.HasKey("TestStudentId");

                    b.ToTable("TestStudent", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.TestContact", b =>
                {
                    b.Property<int>("TestContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestContactId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestContactId");

                    b.ToTable("TestContact", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Infrastructure.Model.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Infrastructure.Model.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestCourse", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestDepartment", "TestDepartment")
                        .WithMany("TestCourses")
                        .HasForeignKey("TestDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestDepartment");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestCourseAssignment", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestCourse", "TestCourse")
                        .WithMany("TestCourseAssignments")
                        .HasForeignKey("TestCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestInstructor", "TestInstructor")
                        .WithMany("TestCourseAssignments")
                        .HasForeignKey("TestInstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCourse");

                    b.Navigation("TestInstructor");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestDepartment", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestInstructor", "Administrator")
                        .WithMany()
                        .HasForeignKey("TestInstructorId");

                    b.Navigation("Administrator");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestEnrollment", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestCourse", "TestCourse")
                        .WithMany("TestEnrollments")
                        .HasForeignKey("TestCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestStudent", "TestStudent")
                        .WithMany("TestEnrollments")
                        .HasForeignKey("TestStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCourse");

                    b.Navigation("TestStudent");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestOfficeAssignment", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestInstructor", "TestInstructor")
                        .WithOne("TestOfficeAssignment")
                        .HasForeignKey("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestOfficeAssignment", "TestInstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestInstructor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Infrastructure.Model.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Infrastructure.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Infrastructure.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Infrastructure.Model.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureTemplate.Infrastructure.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CleanArchitectureTemplate.Infrastructure.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestCourse", b =>
                {
                    b.Navigation("TestCourseAssignments");

                    b.Navigation("TestEnrollments");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestDepartment", b =>
                {
                    b.Navigation("TestCourses");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestInstructor", b =>
                {
                    b.Navigation("TestCourseAssignments");

                    b.Navigation("TestOfficeAssignment");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.ApplicationCore.Entities.ContosoUniversity.TestStudent", b =>
                {
                    b.Navigation("TestEnrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
